import {
  dehydrate,
  HydrationBoundary,
  QueryClient,
} from '@tanstack/react-query'
import Providers from './providers'
import { fetchWebsHydrate } from '@hooks/webs/useWebs'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // eslint-disable-next-line @tanstack/query/stable-query-client
  const queryClient = new QueryClient()

  await queryClient.prefetchQuery({
    queryKey: ['webs', { published: false, withAdminInfo: false }],
    queryFn: () => fetchWebsHydrate(),
  })

  return (
    <html lang="en">
      <body>
        <Providers>
          <HydrationBoundary state={dehydrate(queryClient)}>
            {children}
          </HydrationBoundary>
        </Providers>
      </body>
    </html>
  )
}
